### ISSUE TITLE
SEO improvement

### ISSUE THREAD

**Issue by merodriguezblanco** [transformicons/transformicons#1]
Hi guys, how are you doing?
Long time without contributing to this project!

I was looking at the [transformicons](transformicons.com) website and noticed that there are many things regarding SEO that could be improved:
* Updating meta tags for title, description and keywords.
* Adding a sitemap.xml
* Adding [twitter summary cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary) for sharing on twitter.
* Adding [open graph](http://ogp.me/) support for sharing on facebook.
* Adding [JSON for linked data](https://json-ld.org/).

These additions and changes should improve the SEO of the page so that users can find the page  easier on search engines such as Google or Bing. This would also improve the look and feel of the links to the page when sharing on social networks.

Let me know your thoughts, I'm open to help on this :)

**Comment by grayghostvisuals** [comment]
@merodriguezblanco Since you're an owner now, feel free to go ahead and make adjustments that best fit the project. 🐻

**Comment by dennisgaebel** [comment]
@merodriguezblanco Here is the checklist for the work you listed above.

Anyone is free to start on anything, but please leave a message here when you begin on an item so others know and when completed check it off below.

1. - [ ] Updating meta tags for title, description and keywords.
2. - [ ] Adding a sitemap.xml
3. - [ ] Adding twitter summary cards for sharing on twitter.
4. - [ ] Adding open graph support for sharing on facebook.
5. - [ ] Adding JSON for linked data.

**Comment by dennisgaebel** [comment]
@merodriguezblanco I have a branch for meta and title improvements started. Here is the drafts of what is currently on my branch…

`index.hbs, builder.hbs`
title: Transformicons : The Animated Icon Builder
description: Animated symbols and buttons packaged for Sass & CSS. We also provide a builder that gives developers the ability to select their preferred Transformicons and output for finer control.

`docs.hbs`
title: Transformicons : Documentation
description: References and Explanation for using animated buttons and icons.

**Comment by merodriguezblanco** [comment]
@dennisgaebel thanks for this, it's really helpful!
Planning to start working on this during the weekend :)

**Comment by merodriguezblanco** [comment]
@dennisgaebel  I just pushed a branch `seo-improvements` that I branched out from master.
This branch introduces the following additions to the page:

1. - [x] Add meta tag for keywords.
2. - [x] Adding a sitemap.xml
3. - [x] Adding twitter summary cards for sharing on twitter.
4. - [x] Adding open graph support for sharing on facebook.
5. - [x] Adding JSON for linked data.
6. - [x] Add canonical URLs.
7. - [x] Add robots.txt to exclude some URLs.

Some notes:
* For `2.` I added the plugin [gulp-sitemap](https://www.npmjs.com/package/gulp-sitemap).
* We should add a small logo image to be used for twitter summary cards, open graph and JSON linked data. So far, I've reused a favicon, which can be easily switched.
* In order to use certain config info in the templates, I created the `site.json` file. I was not able to reuse the `site.yml`, so I had to fallback to create the JSON file. 

Please, let me know your thoughts on this.
Feel free to merge this branch to yours `meta-improvements` :)  I did not switch the meta title and description because I saw you switched those in your branch.

**Comment by dennisgaebel** [comment]
@merodriguezblanco Cool thanks 👍  

Yeah the YAML is not being pulled in right now, but I know how to fix this. I will have to remove the JSON logic unfortunately. If you find something like this in the future that doesn't work let me know so we can fix it and you don't waste time building something that will be removed.
