### ISSUE TITLE
GitHub Stars

### ISSUE THREAD

**Issue by dennisgaebel** [transformicons/transformicons#9]
@jfroffice Any news yet about the repo stars we lost? Right now it seems the site still reports the data so it is obviously cached from somewhere even after multiple site updates since the transfer to the org.

[https://github.com/transformicons/transformicons/blob/master/site/js/src/contributors.js#L10](https://github.com/transformicons/transformicons/blob/master/site/js/src/contributors.js#L10)

![screenshot 2017-11-01 14 06 19](https://user-images.githubusercontent.com/13485205/32289766-09541022-bf0e-11e7-9c31-e86d89e4b6dd.png)

**Comment by jfroffice** [comment]
I have tried to contact the sys-admin using [contact form of GitHub](https://github.com/contact).

in wait for an answer...

**Comment by jfroffice** [comment]
The Github reply...

> It looks like you deleted and recreated this repository rather than transferring it:

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

> When you create a new repository, it's not possible to transfer stars from an existing or previous repo, so we can't restore those for you.

> When you transfer a repo, all of the stars will stay intact. We recommend transferring your repository instead in the future.

**Comment by dennisgaebel** [comment]
@jfroffice Interesting. I did in fact transfer this project to an org (this one) and once the transfer was complete I deleted the repo from my personal account (http://github.com/grayghostvisuals/transformicons). This is why the stars got lost along with all issues and such so I'm not sure they are really giving great insight into this issue :\

**Comment by jfroffice** [comment]
> We do have a backup of the previous repository for a short period of time after it's been deleted. The stars would be restored with that repository.

**Comment by dennisgaebel** [comment]
@jfroffice So…restore it? I don't know what else to say.

**Comment by dennisgaebel** [comment]
@jfroffice Any updates on this as of today?

**Comment by jfroffice** [comment]
no update.

I think it is better if you re-contact them directly as the old repo http://github.com/grayghostvisuals/transformicons was owned by you.

I forward you last email I got.
